version: '3.9'

services:
  frontend:
    image: zfarming-frontend
    container_name: zfarming-frontend
    env_file:
      - .env
    build:
      context: .
      args:
        - VITE_APP_TITLE=${VITE_APP_TITLE}
        - VITE_SERVER_URL=${VITE_SERVER_URL}
        - VITE_APP_ENV=${VITE_APP_ENV}
        - VITE_IMAGES_URL=${VITE_IMAGES_URL}
    ports:
      - 3000:80
    restart: always
    networks:
      - zfarming-net

networks:
  zfarming-net:
    name: zfarming-net
  