export enum ROUTE_PATH {
  Root = "/",
  Login = "/login",
  Singup = "/signup",
  Dashboard = "/dashboard",
  User = "/dashboard/user",
  PQRS = "/dashboard/pqrs",
  Farms = "/dashboard/machines",
  Device = "/dashboard/device",
  Profile = "/dashboard/profile",
  Company = "/dashboard/company",
  DeviceByFarm = "/dashboard/farm/:farmId",
  Plant = "/dashboard/plant",
  Galery = "/galery",
}
