export enum ROUTE_TITLE {
  Root = "Root",
  Home = "Inicio",
  Login = "Login",
  Singup = "Signup",
  Dashboard = "Dashboard",
  User = "Usuarios",
  PQRS = "PQRS",
  Device = "Dispositivos",
  Profile = "Perfil de usuario",
  Company = "Compañia",
  Plant = "Plantas",
  Galery = "Galeria de plantas",
  logout = "Cerrar sesión",
}

export enum ROUTE_PATH {
  Root = "/",
  Login = "/login",
  Singup = "/signup",
  Dashboard = "/dashboard",
  User = "/dashboard/user",
  PQRS = "/dashboard/pqrs",
  Device = "/dashboard/device",
  Profile = "/dashboard/profile",
  Company = "/dashboard/company",
  DeviceByFarm = "/dashboard/farm/:farmId",
  DeviceMeasuring = "/dashboard/measuring-history/:deviceId",
  Plant = "/dashboard/plant",
  Galery = "/galery",
  PlantFromGalery = "/plant-from-galery/:plantId",
  ForgotPassword = "/forgot-password",
  RecoverPassword = "/recover-password/:uuid",
}
