export enum ROUTE_PATH {
  Root = "/",
  Login = "/login",
  Singup = "/signup",
  Dashboard = "/dashboard",
  User = "/dashboard/user",
  PQRS = "/dashboard/pqrs",
  Farms = "/dashboard/machines",
  Device = "/dashboard/device",
  Profile = "/dashboard/profile",
  Company = "/dashboard/company",
  DeviceByFarm = "/dashboard/farm/:farmId",
  DeviceMeasuring = "/dashboard/measuring-history/:deviceId",
  Plant = "/dashboard/plant",
  Galery = "/galery",
  PlantByGalery = "/plant-by-galery",
  ForgotPassword = "/forgot-password",
  RecoverPassword = "/recover-password/:uuid",
}
